name: ci

on: [push, pull_request]

jobs:
  ci:
    # Set up operating system
    runs-on: ubuntu-latest

    # Define job steps
    steps:
    - name: Set up Python 3.9
      uses: actions/setup-python@v5
      with:
        python-version: 3.9

    - name: Check-out repository
      uses: actions/checkout@v4

    - name: Sort imports
      uses: isort/isort-action@v1
      with:
        sort-paths: "./reject"

    - name: Black formatting
      uses: psf/black@stable
      with:
        src: "./reject"
        jupyter: true

    - name: Install poetry
      uses: snok/install-poetry@v1

    - name: Install package
      run: poetry install

    - name: Test with pytest
      run: poetry run pytest tests/ --cov=reject --cov-report=xml

    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v4.0.1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        slug: arthur-thuy/reject

    - name: Build documentation
      run: poetry run make html --directory docs/
